#!/bin/bash
XLNX_VIVADO_VERSION=2023.2
XLNX_VIVADO_INSTALLER=FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256_Lin64.bin
#XLNX_VIVADO_INSTALLER=FPGAs_AdaptiveSoCs_Unified_2023.2_1013_2256.tar.gz
XLNX_VIVADO_AUTH_FILE=wi_authentication_key
XLNX_VIVADO_BATCH_CONFIG_FILE=install_config.txt
XLNX_VIVADO_BATCH_CONFIG_FILE_PETALINUX=install_config_petalinux.txt
PETALINUX_PLATFORMS=arm
./${XLNX_VIVADO_INSTALLER} -- -b AuthTokenGen
mv ${HOME}/.Xilinx/wi_authentication_key .
docker image build \
  --build-arg XLNX_VIVADO_VERSION=${XLNX_VIVADO_VERSION} \
  --build-arg XLNX_VIVADO_INSTALLER=${XLNX_VIVADO_INSTALLER} \
  --build-arg XLNX_VIVADO_AUTH_FILE=${XLNX_VIVADO_AUTH_FILE} \
  --build-arg XLNX_VIVADO_BATCH_CONFIG_FILE=${XLNX_VIVADO_BATCH_CONFIG_FILE} \
  --build-arg XLNX_VIVADO_BATCH_CONFIG_FILE_PETALINUX=${XLNX_VIVADO_BATCH_CONFIG_FILE_PETALINUX} \
  --build-arg PETALINUX_PLATFORMS=${PETALINUX_PLATFORMS} \
  -t vivado:${XLNX_VIVADO_VERSION} .
rm -rf wi_authentication_key
